[package]
name = "tokio-io-utility"
version = "0.2.1"
edition = "2018"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "Some helper functions for types impl AsyncWrite."
repository = "https://github.com/NobodyXu/tokio-io-utility.git"

keywords = ["tokio", "async"]
categories = ["asynchronous"]

[dependencies]
tokio = { version = "1.0", features = ["io-util"] }

[dev-dependencies]
tokio-pipe = "0.2.5"
tokio = { version = "1", features = ["rt"] }
