[package]
name = "tokio-io-utility"
version = "0.3.0"
edition = "2018"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "Some helper functions for types impl AsyncWrite."
repository = "https://github.com/NobodyXu/tokio-io-utility.git"

keywords = ["tokio", "async"]
categories = ["asynchronous"]

[features]
mpsc = ["parking_lot", "bytes"]

[dependencies]
tokio = { version = "1.0", features = ["io-util"] }

parking_lot = { version = "0.11.2", optional = true }
bytes = { version = "1", optional = true }

[dev-dependencies]
tokio-pipe = "0.2.5"
tokio = { version = "1", features = ["rt"] }
